/**
 * Step Completion Handler
 * Handles workflow step completion logic
 */

import { prisma } from '@/lib/db';
import { ConversationMessage } from '@/lib/cursor-api/types';
import {
  WorkflowStepData,
  FeatureData,
  NotificationData,
  StepCompletionResult,
  WorkflowStepStatus,
  WorkflowStepType,
  WORKFLOW_STEP_LABELS,
} from './types';
import { extractStepOutput } from './output-extraction';
import { getNextStep, isWorkflowComplete, canManuallyCompleteStep } from './state-management';
import { populateContextFromStep, storeConversationAsContext } from '@/lib/context/auto-populate';
import { detectPRsInConversation } from '@/lib/pull-requests/detection';
import { createPRsFromConversation } from '@/lib/pull-requests/service';

/**
 * Options for handling step completion
 */
export interface StepCompletionOptions {
  step: WorkflowStepData;
  feature: FeatureData;
  allSteps: WorkflowStepData[];
  conversation: ConversationMessage[];
  validateState?: boolean;
}

/**
 * Handle workflow step completion
 * - Updates step status to completed
 * - Extracts and stores step output
 * - Creates notification
 * - Returns next step info
 */
export async function handleStepCompletion(
  options: StepCompletionOptions
): Promise<StepCompletionResult> {
  const { step, feature, allSteps, conversation, validateState = false } = options;

  try {
    // Validate step state if requested
    if (validateState && step.status !== 'in_progress') {
      if (!canManuallyCompleteStep(allSteps, step.stepType)) {
        return {
          success: false,
          stepId: step.id,
          output: null,
          nextStep: null,
          notification: null,
          error: `Cannot complete step "${step.stepType}": previous step not completed`,
        };
      }
    }

    // Extract output from conversation
    const extractionResult = extractStepOutput(step.stepType, conversation);
    const output = extractionResult.success ? extractionResult.output : null;

    // Update step status and output in database
    await updateStepStatus(step.id, 'completed', output || undefined);

    // Auto-populate feature context from step output
    if (output) {
      await populateContextFromStep(feature.id, step.stepType, output);
    }

    // Store conversation in feature context as notes
    if (conversation.length > 0) {
      await storeConversationAsContext(feature.id, conversation);
    }

    // Detect and create PR records from conversation
    // PRs are typically created in implement or submit steps
    if (step.stepType === 'implement' || step.stepType === 'submit') {
      try {
        const detectedPRs = detectPRsInConversation(conversation);
        if (detectedPRs.length > 0) {
          await createPRsFromConversation(
            detectedPRs,
            feature.id,
            step.id,
            step.agentId || null
          );
        }
      } catch (error) {
        // Log error but don't fail step completion if PR detection fails
        console.error('Failed to detect/create PRs from conversation:', error);
      }
    }

    // Get next step
    const nextStep = getNextStep(allSteps, step.stepType);

    // Check if workflow is complete (all steps done)
    const updatedSteps = allSteps.map((s) =>
      s.id === step.id ? { ...s, status: 'completed' as const } : s
    );
    const workflowComplete = isWorkflowComplete(updatedSteps);

    // Create notification
    let notification: NotificationData;
    if (workflowComplete) {
      notification = createWorkflowCompletedNotification(feature);
      // Update feature status to completed
      await updateFeatureStatus(feature.id, 'completed');
    } else {
      notification = createStepCompletedNotification(step, feature, nextStep);
    }

    // Store notification in database
    await createNotification(notification);

    return {
      success: true,
      stepId: step.id,
      output,
      nextStep,
      notification,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return {
      success: false,
      stepId: step.id,
      output: null,
      nextStep: null,
      notification: null,
      error: `Failed to complete step: ${errorMessage}`,
    };
  }
}

/**
 * Create notification for completed step
 */
export function createStepCompletedNotification(
  step: WorkflowStepData,
  feature: FeatureData,
  nextStep: WorkflowStepData | null
): NotificationData {
  const stepLabel = WORKFLOW_STEP_LABELS[step.stepType];
  const nextStepLabel = nextStep ? WORKFLOW_STEP_LABELS[nextStep.stepType] : null;

  return {
    id: '', // Will be generated by database
    type: 'step_completed',
    title: `${stepLabel} Completed`,
    message: `The ${stepLabel.toLowerCase()} step for "${feature.title}" has been completed.${
      nextStep ? ` Next step: ${nextStepLabel}.` : ''
    }`,
    featureId: feature.id,
    stepId: step.id,
    agentId: step.agentId,
    read: false,
    actionUrl: nextStep ? `/features/${feature.id}?step=${nextStep.stepType}` : `/features/${feature.id}`,
    actionLabel: nextStep ? `Start ${nextStepLabel}` : null,
    createdAt: new Date(),
  };
}

/**
 * Create notification for completed workflow
 */
export function createWorkflowCompletedNotification(
  feature: FeatureData
): NotificationData {
  return {
    id: '', // Will be generated by database
    type: 'workflow_completed',
    title: 'Workflow Complete',
    message: `All workflow steps for "${feature.title}" have been completed!`,
    featureId: feature.id,
    stepId: null,
    agentId: null,
    read: false,
    actionUrl: `/features/${feature.id}`,
    actionLabel: 'View Feature',
    createdAt: new Date(),
  };
}

/**
 * Update step status in database
 */
export async function updateStepStatus(
  stepId: string,
  status: WorkflowStepStatus,
  output?: string
): Promise<void> {
  await prisma.workflowStep.update({
    where: { id: stepId },
    data: {
      status,
      output,
    },
  });
}

/**
 * Store step output in database
 */
export async function storeStepOutput(
  stepId: string,
  output: string
): Promise<void> {
  await prisma.workflowStep.update({
    where: { id: stepId },
    data: {
      output,
    },
  });
}

/**
 * Update feature status in database
 */
export async function updateFeatureStatus(
  featureId: string,
  status: string
): Promise<void> {
  await prisma.feature.update({
    where: { id: featureId },
    data: {
      status,
    },
  });
}

/**
 * Create notification in database
 */
export async function createNotification(
  notification: NotificationData
): Promise<NotificationData> {
  const created = await prisma.notification.create({
    data: {
      type: notification.type,
      title: notification.title,
      message: notification.message,
      featureId: notification.featureId,
      stepId: notification.stepId,
      agentId: notification.agentId,
      read: notification.read,
      actionUrl: notification.actionUrl,
      actionLabel: notification.actionLabel,
    },
  });

  return {
    ...notification,
    id: created.id,
    createdAt: created.createdAt,
  };
}

/**
 * Mark step as blocked
 */
export async function markStepBlocked(
  stepId: string,
  reason?: string
): Promise<void> {
  await prisma.workflowStep.update({
    where: { id: stepId },
    data: {
      status: 'blocked',
      output: reason ? `BLOCKED: ${reason}` : undefined,
    },
  });
}

/**
 * Mark step as in progress with agent ID
 */
export async function markStepInProgress(
  stepId: string,
  agentId: string
): Promise<void> {
  await prisma.workflowStep.update({
    where: { id: stepId },
    data: {
      status: 'in_progress',
      agentId,
    },
  });
}

/**
 * Reset step to pending status
 */
export async function resetStepToPending(stepId: string): Promise<void> {
  await prisma.workflowStep.update({
    where: { id: stepId },
    data: {
      status: 'pending',
      agentId: null,
      output: null,
    },
  });
}
